#volumes:
#  data:
#
#services:
#  postgres:
#    image: postgres:latest # образ PostgreSQL
#    environment:
#      - POSTGRES_USER=postgres # имя пользователя системы PostgreSQL
#      - POSTGRES_PASSWORD=postgres # пароль
#    ports:
#      - 8088:5432 # открыть внешний доступ к контейнеру по порту 8088
#    volumes:
#      - data:/var/lib/postgresql


version: '1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "8088:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres-data: